// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfm1LncAgTZtKj0G94U_S8mzCQ4w7Lzdk',
    appId: '1:475965111579:web:ca0d2a8e9856f03a7367be',
    messagingSenderId: '475965111579',
    projectId: 'mylatestproject-db157',
    authDomain: 'mylatestproject-db157.firebaseapp.com',
    storageBucket: 'mylatestproject-db157.appspot.com',
    measurementId: 'G-DW8GYVKXNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC66PattXSre2HjB-uauUd5dvmyGIB_Qt8',
    appId: '1:475965111579:android:0acde360e35a61757367be',
    messagingSenderId: '475965111579',
    projectId: 'mylatestproject-db157',
    storageBucket: 'mylatestproject-db157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGP4pTh-Lh_7DtTYAC6mZxLrokuk9xR_4',
    appId: '1:475965111579:ios:9b726342bb8495807367be',
    messagingSenderId: '475965111579',
    projectId: 'mylatestproject-db157',
    storageBucket: 'mylatestproject-db157.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGP4pTh-Lh_7DtTYAC6mZxLrokuk9xR_4',
    appId: '1:475965111579:ios:9b726342bb8495807367be',
    messagingSenderId: '475965111579',
    projectId: 'mylatestproject-db157',
    storageBucket: 'mylatestproject-db157.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfm1LncAgTZtKj0G94U_S8mzCQ4w7Lzdk',
    appId: '1:475965111579:web:d7bff62dbd916c1e7367be',
    messagingSenderId: '475965111579',
    projectId: 'mylatestproject-db157',
    authDomain: 'mylatestproject-db157.firebaseapp.com',
    storageBucket: 'mylatestproject-db157.appspot.com',
    measurementId: 'G-W54ZSW02B2',
  );
}
